services:
  piper-tts-server:
    container_name: piper-tts-server
    # build: .
    build: 
      context: .
      dockerfile: Dockerfile
      # enable if you have nvidia gpu
      # dockerfile: Dockerfile.cuda 
    image: piper-tts-server:latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - DEFAULT_PIPER_MODEL=ar_JO-kareem-medium

    # enable if you have nvidia gpu
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]